apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devesh11411/backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: <host>
        - name: DB_USERNAME
          value: <username>
        - name: DB_PASSWORD
          value: <password>
        - name: PORT
          value: <port>
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: backend
